### ISSUE TITLE
`rye test` should expose pytest markers

### ISSUE THREAD

**Issue by Tomperez98** [astral-sh/rye#1007]
`pytest` allow to mark tests via `@pytest.mark.unit()`, `@pytest.mark.integration()` and run all marked tests with:
- `pytest -m unit`
- `pytest -m integration`

`rye` should expose the same with:
- `rye test -m unit`
- `rye test -m integration`

**Comment by khvn26** [comment]
I'm pretty sure you're able to do this by running:

```sh
rye test -- -m unit
rye test -- -m integration
```
