### ISSUE TITLE
Export `VIRTUAL_ENV` when executing `python` inside a rye-managed project

### ISSUE THREAD

**Issue by ma-sadeghi** [astral-sh/rye#1043]
Not sure if this was intentionally left out, but it'd be great if `VIRTUAL_ENV` was set when executing `python` inside a rye-managed project so third-party programs can still find the `.venv` path.

**Comment by bluss** [comment]
Do you have an example of a tool that is helped by this?

**Comment by ma-sadeghi** [comment]
Yes, [`pyjuliapkg`](https://github.com/JuliaPy/pyjuliapkg) is a tool for managing Julia dependencies from Python. It relies on `VIRTUAL_ENV` to decide where to put the Julia dependencies:

https://github.com/JuliaPy/pyjuliapkg/blob/main/src/juliapkg/state.py#L61

**Comment by bluss** [comment]
Just as extra information for context, most python tools don't need this since if the currently running python is in a virtual environment that can be detected and the recommended way to detect does not use VIRTUAL_ENV, instead something along these lines https://stackoverflow.com/a/1883251

**Comment by ma-sadeghi** [comment]
Makes sense. I opened up a separate issue in the source repository to hopefully address it at root. Just to make sure I understood, would you still consider exporting `VIRTUAL_ENV`? or since it's not the proper way, you'd rather not? Thanks!

**Comment by bluss** [comment]
Maybe @mitsuhiko has better insight into what's best to do about that

**Comment by mitsuhiko** [comment]
We do set `VIRTUAL_ENV` for scripts, but not for Python itself. Reason being that `python` itself can discover the virtualenv with `sys.prefix`.  I don't think it's correct for code to use anything other than that to discover virtualenvs.

**Comment by ma-sadeghi** [comment]
I agree, and so do the the devs/maintainers of the conflicting package (`pyjuliapkg`). (And are willing to accept a PR that fixes the way virtualenv is identified.) So, I'm closing this issue. Thanks for the follow up :)
