### ISSUE TITLE
Installing rye with --yes does not install interactive defaults

### ISSUE THREAD

**Issue by eifinger** [astral-sh/rye#1081]
When I install rye in interactive mode it will put `use-uv=true` as a default in the config file as defined in https://github.com/astral-sh/rye/blob/43ac3a3ebfe2fd647e7b9a9fca723eeb37194b7d/rye/src/cli/rye.rs#L589-L602

When the interactive mode is disabled https://github.com/astral-sh/rye/blob/43ac3a3ebfe2fd647e7b9a9fca723eeb37194b7d/rye/src/cli/rye.rs#L194 nothing is being put in the config file.

I think this should be aligned.

**Comment by charliermarsh** [comment]
I think this is less relevant now that uv is the default when omitted... but agree it's a bit odd.
