### ISSUE TITLE
Unable to connect to https://rye-up.com/get ?

### ISSUE THREAD

**Issue by kissge** [astral-sh/rye#1111]
I'm sorry if this isn't quite right place to report; currently Rye's recommended installation method is not possible as the website is down.

**Comment by charliermarsh** [comment]
Strange, nothing here has changed recently...

**Comment by edran** [comment]
Was about to alert on twitter, but glad I checked github first. @charliermarsh holler if you need any help!

**Comment by charliermarsh** [comment]
Thanks, I'm looking into it now. Sorry about that.

**Comment by aethiopicuschan** [comment]
I was able to download the script when I accessed it directly in Chrome, but in curl I get `curl: (7) Failed to connect`.
Reference.

**Comment by charliermarsh** [comment]
In the interim, you can run `curl https://raw.githubusercontent.com/astral-sh/rye/main/scripts/install.sh | sh`.

**Comment by faysou** [comment]
The website is completely down.

**Comment by my1e5** [comment]
If you need to access the documentation, you can serve mkdocs locally

```
$ git clone https://github.com/astral-sh/rye
$ cd rye/
$ rye sync

**Comment by pablo8itall** [comment]
> In the interim, you can run `curl -sSf https://raw.githubusercontent.com/astral-sh/rye/main/scripts/install.sh | sh`.

I get: 

sh: 2: set: Illegal option -o pipefail 

This is on Ubuntu 22.04.3 LTS WSL. From google this happens because that option not working on dash shell, /bin/sh links to  /bin/dash.

Workaround:
`curl -sSf https://raw.githubusercontent.com/astral-sh/rye/main/scripts/install.sh
chmod +x install.sh
./install.sh`

**Comment by vhdirk** [comment]
Can confirm, website is down

**Comment by charliermarsh** [comment]
I'm working on getting the domain back up -- there was kind of a perfect storm of events and now it's stuck waiting on some third parties. I can share more details once it's resolved, but ultimately it's my fault.

In the meantime, I'm going to move the docs etc. to a subdomain on `astral.sh`. We can redirect back to `rye-up.com` (or vice versa) once it's restored.

**Comment by charliermarsh** [comment]
Re-opening since `rye-up.com` is still down. But all the docs, references, etc. now point to `https://rye.astral.sh`.

For example:
```sh
curl -sSf https://rye.astral.sh/get | bash
```

**Comment by edran** [comment]
Hugsops! Thank you @charliermarsh for quickly resolving this!

**Comment by charliermarsh** [comment]
Thank you for the kind words @edran, I appreciate it!

**Comment by mitsuhiko** [comment]
I'm sorry we screwed something up there when I handed the domain over to Astral. Looks like we're now in for some waiting as neither one of our registrars is entirely sure what's going on :(

**Comment by edran** [comment]
Hugops to you too @mitsuhiko--happens to the best of us!

Modulo the unfortunate CI breakages, I do think there's silver lining to be found with the new setup, at least wrt. user confidence :) `rye` and `astral.sh` together IMO make each other's brands stronger.

**Comment by kissge** [comment]
Thanks for all the great work!!

**Comment by charliermarsh** [comment]
Okay, the domain is finally back up. I have it redirecting to `rye.astral.sh`, so either domain will work. Apologies everyone and thanks for your patience.
