### ISSUE TITLE
Can’t check the rye version

### ISSUE THREAD

**Issue by Fulminare137** [astral-sh/rye#1149]
### Steps to Reproduce

1. Installed rye using curl -sSf https://rye.astral.sh/get | bash
2. used pip-tools instead of uv
4. Set the path to by myself to  source "$HOME/.rye/env” in  ~/.zprofile
4. i am using mac on arm and a newbie

### Expected Result

Something like "rye --version
rye 0.34.0
commit: 0.34.0 (d31340178 2024-05-20)
platform: macos (aarch64)
self-python: cpython@3.12.3
symlink support: true
uv enabled: false" ?

### Actual Result

<img width="682" alt="image" src="https://github.com/astral-sh/rye/assets/72355599/86bfd097-f7d3-4343-b0c7-f4be36c6adcd">

### Version Info

error: unexpected argument found

**Comment by phi-friday** [comment]
Use `rye --version` instead of `rye -- version`

**Comment by charliermarsh** [comment]
Yup `rye --version` looks right to me!
