### ISSUE TITLE
Add ; platform_system tag to requirements.lock where applicable

### ISSUE THREAD

**Issue by hanerlend** [astral-sh/rye#1166]
Some times a requirements-file might include OS-specific requirements. This can be a problem if you develop on Windows, and want to deploy your project with Docker.

Example using Django + Daphne:

```console
rye init newproject --virtual
cd newproject
rye add django daphne
rye sync
```

When trying to build a Docker image (which is linux, not windows), the build fails. To fix this, edit requirements.lock :

```
twisted-iocpsupport==1.0.4 ; platform_system == "Windows"
```

Coming from Poetry, this happened automatically. It would be really nice if this would also be implemented in Rye. 😊

**Comment by bluss** [comment]
This is possible with uv since yesterday ;) https://github.com/astral-sh/uv/pull/4505

**Comment by hanerlend** [comment]
> This is possible with uv since yesterday ;) [astral-sh/uv#4505](https://github.com/astral-sh/uv/pull/4505)

Nice! 🥳👏 Tested in Rye, and I see it's not there yet. Hopefully we won't have to exclude Windows-only deps with ; platform_system == "Windows" much longer. 😊

**Comment by charliermarsh** [comment]
I can do a Rye release today, hopefully.

**Comment by hanerlend** [comment]
Upgraded to Rye version 0.36.0 today.

requirements.lock still does not include the platform tag;

```
twisted-iocpsupport==1.0.4
```
will still fail when building a docker image.

**Comment by bluss** [comment]
@hanerlend New flag is rye sync --universal or set [tool.rye] universal = true in pyproject.toml. It works for me.

**Comment by charliermarsh** [comment]
:thumbsup: Yeah it's opt-in for now
