### ISSUE TITLE
Cannot fetch cpython@3.12.4

### ISSUE THREAD

**Issue by ShravanSunder** [astral-sh/rye#1174]
### Steps to Reproduce

cpython 3.12.4 can't be fetched, its already in [Indygreg's Portable Python Builds](https://github.com/indygreg/python-build-standalone) for CPython

use rye toolchain fetch cpython@3.12.4

### Expected Result

being able to fetch it as its in the portable python builds

### Actual Result

![2024-06-27 0616 Brave Browser New Issue · astral-shrye](https://github.com/astral-sh/rye/assets/5294949/8ad7bc5e-620a-4b5b-b3dc-738edac1ed71)

### Version Info

⚡➜ ~ rye --version
rye 0.35.0
commit: 0.35.0 (2024-06-24)
platform: macos (aarch64)
self-python: cpython@3.12.2
symlink support: true
uv enabled: true

**Comment by ShravanSunder** [comment]
It caused a problem since homebrew updated to 3.12.4 and rye didn't.  something went strange with my existing venvs

**Comment by zanieb** [comment]
Hi! That version is not released yet, it's in the build but we [haven't cut a new release](https://github.com/indygreg/python-build-standalone/releases) of `python-build-standalone`.

**Comment by ShravanSunder** [comment]
ah i'll close it then.
