### ISSUE TITLE
🗎 Behaviour quirks link broken in FAQ

### ISSUE THREAD

**Issue by galenseilis** [astral-sh/rye#1176]
### Steps to Reproduce

The [FAQ](https://rye.astral.sh/guide/faq/#python-interactive-prompt-input-messed-up) says

> For solutions to this issue, read the [behavior quirks guide](https://python-build-standalone.readthedocs.io/en/latest/quirks.html) in the Standalone Python Builds documentation for solutions.

However, [that link](https://python-build-standalone.readthedocs.io/en/latest/quirks.html) is giving me a 404 message.

### Expected Result

I expected to be redirected to a working web page somewhere.

### Actual Result

I got a 404 error.

### Version Info

Not applicable.

### Stacktrace

Not applicable.

**Comment by charliermarsh** [comment]
Thanks!

**Comment by zanieb** [comment]
For reference, it's at https://gregoryszorc.com/docs/python-build-standalone/main/quirks.html

**Comment by galenseilis** [comment]
@zanieb Thanks for the link! 🙏
