### ISSUE TITLE
Print message when executing `rye build` on a virtual project

### ISSUE THREAD

**Issue by pandaxtc** [astral-sh/rye#1213]
It might be helpful to log some kind of message when `rye build` is executed in a virtual project. The current behavior of silently exiting may be confusing if one doesn't understand what `virtual` does or has forgotten/hasn't noticed that the project is virtual. This tripped me up for a moment today, and I found https://github.com/astral-sh/rye/issues/1204 as well.

**Comment by nazq** [comment]
Put in this simple PR for this issue, I hit this some time back and it took me a min to figure out what was happening https://github.com/astral-sh/rye/pull/1227

**Comment by charliermarsh** [comment]
Closed by https://github.com/astral-sh/rye/pull/1227.
