### ISSUE TITLE
IPython not working with Rye `.venv`

### ISSUE THREAD

**Issue by jamesbraza** [astral-sh/rye#1247]
### Steps to Reproduce

It seems IPython doesn't work with a `.venv` made by `rye sync`:

```none
> rye sync
Reusing already existing virtualenv
Generating production lockfile: /path/to/repo/requirements.lock
Generating dev lockfile: /path/to/repo/requirements-dev.lock
Installing dependencies
Resolved 65 packages in 540ms
   Built pqapi @ file:///path/to/repo
Prepared 1 package in 526ms
Uninstalled 1 package in 0.53ms
Installed 1 package in 1ms
 - pqapi==6.3.1.dev10+g13987e0.d20240720 (from file:///path/to/repo)
 + pqapi==6.3.1.dev10+g13987e0.d20240720 (from file:///path/to/repo)
Done!
>  source .venv/bin/activate
> which python
/path/to/repo/.venv/bin/python
> pip list
Package           Version
----------------- -------
asttokens         2.4.1
decorator         5.1.1
executing         2.0.1
ipython           8.26.0
jedi              0.19.1
matplotlib-inline 0.1.7
parso             0.8.4
pexpect           4.9.0
pip               24.0
prompt_toolkit    3.0.47
ptyprocess        0.7.0
pure-eval         0.2.2
Pygments          2.18.0
six               1.16.0
stack-data        0.6.3
traitlets         5.14.3
wcwidth           0.2.13
>  ipython
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'IPython'
> python -m ipython
/path/to/repo/.venv/bin/python: No module named ipython
```

### Expected Result

IPython to work in a Rye `.venv`

### Actual Result

>  ipython
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'IPython'

### Version Info

rye 0.36.0
commit: 0.36.0 (2024-07-07)
platform: macos (aarch64)
self-python: cpython@3.12.3
symlink support: true
uv enabled: true

**Comment by bluss** [comment]
What's the complete steps to reproduce here? (From rye init, rye add etc). Is IPython installed in the current rye project or not (I suppose it's not?)

**Comment by jamesbraza** [comment]
Yeah here is a full repro:

```bash
> rye init project
> cd project
> rye lock
> source .venv/bin/activate
> pip install ipython
> ipython
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'IPython'
```

I realized the issue is that `rye`-made `.venv`'s don't seem to work with `pip`:

```bash
> which python
/Users/user/code/project/.venv/bin/python
> which pip
pip: aliased to noglob pip3
 > which pip3
/Users/user/.pyenv/shims/pip3
```

Do you know why `pip` is not properly aliased to the `.venv` when it's activated?

**Comment by charliermarsh** [comment]
They don't include a user-exposed pip at all. It's part of Rye's philosophy: https://rye.astral.sh/philosophy/.

**Comment by jamesbraza** [comment]
Oh I see, sorry for the false report here. Good to know and appreciate the response!

**Comment by jamesbraza** [comment]
Thanks @bluss , appreciate the follow up. Actually if you have a second, I am curious about this:

> Ipython has a feature where it can interface with venvs it's not installed in

I just set up something like:

1. `pyenv global 3.12.4`, with `ipython` installed
2. `rye` local with Python 3.12.4, no `ipython` installed/added, `rye`'s `.venv` activated

Do you know how to trigger that IPython feature such that it falls back onto what's installed in system Python?

**Comment by bluss** [comment]
The recipe is like this

Activate the venv that has the libraries you want to import (the 2).
Run ipython using the python where it's installed. That's /path/to/ipython/environment/bin/ipython  (`/path/to/ipython/environment/bin/python -m IPython` should also be an alternative)

**Comment by jamesbraza** [comment]
Ah I follow and thank you. So in my case then what I'd do is:

```bash
source .venv/bin/activate
/Users/user/.pyenv/shims/python -m IPython
```

Case closed, cheers!
