### ISSUE TITLE
Crashes if run with different casing for `rye.exe` (ex: `rye.EXE`).

### ISSUE THREAD

**Issue by itsjohncs** [astral-sh/rye#1284]
### Steps to Reproduce

On Windows, run `rye` using its full path, but using different casing for its name than what's recorded on the filesystem. For example, if `rye` is installed to `C:\Users\johns\.rye\shims\rye.exe` you can reproduce this bug by running `C:\Users\johns\.rye\shims\RYE.EXE` or `C:\Users\johns\.rye\shims\rye.EXE`.

As an example for the remaining sections of this report, I will use:

```
C:\Users\johns\.rye\shims\rye.EXE --version
```

### Expected Result

`rye` should print out the version and then exit.

### Actual Result

```
> C:\Users\johns\.rye\shims\rye.EXE --version
error: target shim binary 'rye.EXE' not found
```

### Version Info

```
> C:\Users\johns\.rye\shims\rye.exe --version
rye 0.37.0
commit: 0.37.0 (09b67c469 2024-07-20)
platform: windows (x86_64)
self-python: cpython@3.12.4
symlink support: true
uv enabled: true
```

### Stacktrace

```
> $env:RUST_BACKTRACE=1; C:\Users\johns\.rye\shims\rye.EXE --version; $env:RUST_BACKTRACE=$null
error: target shim binary 'rye.EXE' not found

Stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: BaseThreadInitThunk
  14: RtlUserThreadStart
```

**Comment by itsjohncs** [comment]
Ah! I forgot to add the *why* to this esoteric issue.

This came up while creating a [pre-commit](https://pre-commit.com) hook for `rye`. `pre-commit` will search the `PATH` and apply `PATHEXT` itself on Windows ([source](https://github.com/pre-commit/pre-commit/blob/faa6f8c70ccef865884adb0cb079c8162013bf19/pre_commit/parse_shebang.py#L31)) and thus create a path with odd casing. I was able to work around this issue easily enough though ([source](https://github.com/itsjohncs/rye-pre-commit/blob/main/.pre-commit-hooks.yaml)).

**Comment by charliermarsh** [comment]
Hey @itsjohncs good to see you. Should be fixed in https://github.com/astral-sh/rye/pull/1286.

**Comment by itsjohncs** [comment]
It’s good to see you too! You’ve made some wonderful tools.

Thank you for such a quick fix!
