### ISSUE TITLE
Use `rye new project` replace `rye init project && cd project && rye sync`

### ISSUE THREAD

**Issue by wngtk** [astral-sh/rye#1321]
`rye init` can sometimes just want to do the following and see, but it's easy to initialize a Python project in the wrong place. How about rye adding a new command, like `cargo new`, to create a project and run `rye sync`?

**Comment by Zaloog** [comment]
@wngtk 
Isnt defining an alias on your own for your shell an easy solution to this?
I also created a TUI for rye (rye-tui) with basic functionality, that way you can manage projects with an UI and it automatically uses the corresponding working directory of the project when adding packages or syncing
