### ISSUE TITLE
Annotations are no longer added into output lockfile

### ISSUE THREAD

**Issue by jojo0severo** [astral-sh/rye#1402]
### Steps to Reproduce

Tun `rye sync` in the latest version (`0.40.0`)

### Expected Result

Lockfile with each dependency annotated with the packages that require it

Example:
```
annotated-types==0.7.0
    # via pydantic
anyio==4.6.0
    # via httpx
    # via sse-starlette
    # via starlette
    # via watchfiles
``` 

### Actual Result

Only the packages without any annotations.
```
annotated-types==0.7.0
anyio==4.6.0
```

### Version Info

0.40.0

### Stacktrace

No stacktrace, but I suspect the change was when removing pip tools support:
https://github.com/astral-sh/rye/commit/2c690505e955fd9c5773b4059aee05269a90b49d#diff-7e6a2165349b5c6cc1415ede1286e4e15f41a8f5b2f88b26efb038054b483a10

Note that the --annotate flag was removed, but I'm not familiar enough with the project to be sure.

**Comment by charliermarsh** [comment]
I'll take a look, thanks.

**Comment by charliermarsh** [comment]
I think 87e0cecb4091a07f6ad940d44de8fc490ab31542 is the culprit.
