### ISSUE TITLE
An official setup-rye for github action

### ISSUE THREAD

**Issue by Mai0313** [astral-sh/rye#1427]
I made one for myself [link](https://github.com/marketplace/actions/setup-astral-rye), but I hope there is an official one we can use since all my project and all project on my company are relied on `rye`.

I know there is `setup-uv` action, but I still hope we can have it in case we wanna use rye script

**Comment by charliermarsh** [comment]
I recommend https://github.com/marketplace/actions/python-setup-rye. @eifinger also worked on the official [setup-uv](https://github.com/astral-sh/setup-uv) action.

**Comment by Mai0313** [comment]
> I recommend https://github.com/marketplace/actions/python-setup-rye. @eifinger also worked on the official [setup-uv](https://github.com/astral-sh/setup-uv) action.

oh i thought it is not an official, but it looks good! thanks

**Comment by charliermarsh** [comment]
Yeah the [setup-rye](https://github.com/marketplace/actions/python-setup-rye) action isn't "official" necessarily (it's not in the Astral GitHub Org) but the author works on the official uv action :)
