### ISSUE TITLE
Rye uses indygreg's freethreaded builds

### ISSUE THREAD

**Issue by Alexis-D** [astral-sh/rye#1436]
e.g. https://github.com/astral-sh/rye/blob/7b8b1016ad6b0708639bfeb43c65911d40da9e0d/rye/src/sources/generated/python_downloads.inc#L104-L108

It's unclear whether this was intended as this was introduced automatically by https://github.com/astral-sh/rye/pull/1406. Per <https://docs.python.org/3/whatsnew/3.13.html> "support for running in a [free-threaded mode](https://docs.python.org/3/whatsnew/3.13.html#whatsnew313-free-threaded-cpython)" is "experimental".

Freethreaded CPython builds can cause issues e.g. https://github.com/pydantic/pydantic-core/issues/1548 that don't happen with the regular builds.

Would it make sense to download non-freethreaded builds by _default_ (and maybe let folks opt into freethreaded builds, e.g. by requesting a `3.13.0t` build rather than a `3.13.0`)?

**Comment by zanieb** [comment]
Yeah this seems like a mistake / bug.
