### ISSUE TITLE
can't run global package after install  

### ISSUE THREAD

**Issue by gokulyc** [astral-sh/rye#147]
### Steps to Reproduce

  1. rye install pdm (pdm.exe is in User directory "C:\Users\[username]\.rye\shims\pdm.exe")
  2. Trying to run command pdm. (Expecting pdm to available globally)

![image](https://github.com/mitsuhiko/rye/assets/13468848/d14ff834-21b6-439d-ac3c-7e9e4c8eb76f)

### Expected Result

Expecting pdm to available globally in command prompt

### Actual Result

![WindowsTerminal_p9yPpymyI4](https://github.com/mitsuhiko/rye/assets/13468848/4daded97-12d9-49f7-bb53-2e798d620dfb)

### Version Info

at 15:32:20 ❯ rye --version
rye 0.1.0
commit: unknown (75fb742da 2023-05-12)
platform: windows (x86_64)
self-python: cpython@3.10

**Comment by T-256** [comment]
run command doesn't support global rye packages.

**Comment by T-256** [comment]
run command doesn't support global rye packages.

**Comment by mitsuhiko** [comment]
What happens if you run `C:\Users\[username]\.rye\shims\pdm.exe` directly? Does it succeed? It almost sounds like your shims are not on the `PATH`.

**Comment by T-256** [comment]
`run` command only uses current project available venv (auto creates if not exists):
```
E:\ryetest>rye init
success: Initialized project in E:\ryetest\.
  Run `rye sync` to get started

E:\ryetest>rye pin test@3.7.9
pinned test@3.7.9 in E:\ryetest\.python-version

E:\ryetest>rye run python
Initializing new virtualenv in E:\ryetest\.venv
Python version: test@3.7.9
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:01:55) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

could it add shims path to current shell env?
```

E:\>mkdir empty & cd empty

E:\empty>rye install pycowsay
Error: package already installed

E:\empty>rye run pycowsay hi
Error: did not find pyproject.toml

E:\empty>rye run --list
Error: did not find pyproject.toml

E:\empty>
```

**Comment by gokulyc** [comment]
Got it C:\Users\[user]\.rye\shims is not in path. I thought it is added automatically. Fixed it, Its working now.

How to list globally installed packages?
