### ISSUE TITLE
support dependency groups

### ISSUE THREAD

**Issue by Roger-luo** [astral-sh/rye#421]
I think this is a very convenient feature that `pdm` and `poetry` has. When I try to make a package that may use CUDA, I need to have a dependency that depends on hardware configurations, and a package manager has no means to know that thus I believe the best way is to let users decide which group of dependencies they should install. This is like the features at the package level.

Currently, there is no way to specify both CPU and GPU dependencies with rye within one `pyproject.toml`, cargo also has something similar that allows one to specify dependencies based on the current crates' features. And I don't see a way of passing "extra"s in python's `pyproject.toml` (e.g pass the extra `[cuda12]` across packages) I hope this could be something rye can fix

**Comment by rbavery** [comment]
It also would be great to be able to build wheels by specifying dependency groups. I want to build a CPU version of my package that uses the CPU version of pytorch, and another that uses the GPU version and also installs a few other packages. [poetry doesn't support this](https://github.com/python-poetry/poetry/issues/6727#issuecomment-1270822211) even though it has dependency groups.

**Comment by nikhilweee** [comment]
Came here to say it would be nice to see this feature. Although I'm a bit confused as to what do we mean by dependency groups.

1. Python projects already have a way of specifying [extras](https://packaging.python.org/en/latest/specifications/dependency-specifiers/#extras) under `project.optional-dependencies` in `pyproject.toml`. Is this what we are referring to?
2. There's also a draft [PEP-735](https://peps.python.org/pep-0735) which is also called dependency groups. Although this talks about adding a top level `[dependency-groups]` table in `pyproject.toml`, amongst other things.

If we're referring to extras, it's further confusing that rye currently uses the term `features` for selecting extras when adding packages. `rye add flask --features async`. Ironically, rye doesn't let you specify those extras when building your own package.

**Comment by sirfz** [comment]
> ```
> rye sync --features web
> ```

This actually doesn't work for me, must have something to do with a limitation in virtual packages (#639)

**Comment by jmcvetta** [comment]
It would be pretty cool if Rye produced a separate lockfile for each dependency group.  

I.e. if we have a dependency group `foobar`, then running `rye sync --features foobar` will produce a lockfile `requirements-foobar.lock`.

Then in my `Dockerfile` it's super easy to install this dependency group:

```
 uv pip install -r requirements-foobar.lock
```

**Comment by Roger-luo** [comment]
FYI. https://github.com/astral-sh/uv/issues/8090 I think this can be closed as people/new features are moving to `uv`.
