### ISSUE TITLE
Intermittent `rye-up.com/get` connection failures

### ISSUE THREAD

**Issue by MartinBernstorff** [astral-sh/rye#780]
### Steps to Reproduce

```docker
ENV RYE_HOME="/opt/rye"
ENV PATH="$RYE_HOME/shims:$PATH"
ENV RYE_INSTALL_OPTION="--yes"
ENV RYE_TOOLCHAIN="/usr/local/bin/python"
ENV RYE_VERSION=0.26.0
RUN curl -sSf https://rye-up.com/get > /tmp/get-rye.sh
```

<img width="576" alt="image" src="https://github.com/astral-sh/rye/assets/8526086/eea01f3e-a5f6-45da-b420-293801f3562e">

Getting this in both Github Actions and locally for the last ~12h. Perhaps a CDN issue after migrating to the new website?

### Expected Result

Rye installs.

### Actual Result

Failure.

### Version Info

0.26.0

**Comment by mitsuhiko** [comment]
We're in the process of transferring the domain and registrar. It might be that the change to the NS record has not properly propagated yet everywhere :(
