### ISSUE TITLE
`rye fmt` or `rye lint` error

### ISSUE THREAD

**Issue by noahlias** [astral-sh/rye#795]
### Steps to Reproduce

Run `rye fmt` or `rye lint`

### Expected Result

No Error.

### Actual Result

error: No such file or directory (os error 2)

### Version Info

rye 0.27.0
commit: 0.27.0 (43ee4fce0 2024-02-26)
platform: macos (aarch64)
self-python: cpython@3.12
symlink support: true
uv enabled: true

### Stacktrace

λ RUST_BACKTRACE=1 rye fmt
error: No such file or directory (os error 2)

Stack backtrace:
   0: std::backtrace::Backtrace::create
   1: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
   2: rye::utils::ruff::execute_ruff
   3: rye::cli::fmt::execute
   4: rye::cli::execute
   5: rye::main
   6: std::sys_common::backtrace::__rust_begin_short_backtrace
   7: std::rt::lang_start::{{closure}}
   8: std::rt::lang_start_internal
   9: _main

**Comment by ischaojie** [comment]
Can you provide more detailed steps to reproduce the error?

**Comment by noahlias** [comment]
> Can you provide more detailed steps to reproduce the error?

[![asciicast](https://asciinema.org/a/2Yu4GPbpk2Why6zwjPPpCOzAX.svg)](https://asciinema.org/a/2Yu4GPbpk2Why6zwjPPpCOzAX)

**Comment by ischaojie** [comment]
I used the same steps and did not reproduce the issue. I suspect that the corresponding code files were not created during `rye init`. What‘s the result when running `ls -lR .`?

**Comment by noahlias** [comment]
> I used the same steps and did not reproduce the issue. I suspect that the corresponding code files were not created during `rye init`. What‘s the result when running `ls -lR .`?

![image](https://github.com/astral-sh/rye/assets/3949397/3dce9f09-ca2f-44e1-858f-48a4bfdb9028)

![image](https://github.com/astral-sh/rye/assets/3949397/e5cb2cfb-2528-4608-b950-4ed141999c27)

**Comment by j178** [comment]
It looks like the `ruff` binary is missing, rye self venv might be corrupted. Could you try running `rm -rf ~/.rye/self && rye fmt` to see if that works? @noahlias

**Comment by noahlias** [comment]
> It looks like the `ruff` binary is missing, rye self venv might be corrupted. Could you try running `rm -rf ~/.rye/self && rye fmt` to see if that works? @noahlias

Ok, it works. 

I didn't change the self-directory, so weird.
