### ISSUE TITLE
rye sync fails with "failed fetching toolchain ahead of sync"

### ISSUE THREAD

**Issue by selectnull** [astral-sh/rye#798]
### Steps to Reproduce

```
$ rye init foo
success: Initialized project in [...]foo
  Run `rye sync` to get started

$ cd foo

$ rye sync
error: failed fetching toolchain ahead of sync

Caused by:
    unknown version cpython-aarch64-macos@3.11.0
```

I have tried to reinstall rye itself, it didn't help.

### Expected Result

I expected the project to be `sync`ed. 

### Actual Result

I have an older project that still works, tried with multiple rye versions (from 0.23 to 0.27). Any new project created, it fails on sync. I can't run `python` either.

```
$ python
error: sync ahead of shim resolution failed

Caused by:
    0: failed fetching toolchain ahead of sync
    1: unknown version cpython-aarch64-macos@3.11.0
```

### Version Info

```
$ rye --version
rye 0.27.0
commit: 0.27.0 (43ee4fce0 2024-02-26)
platform: macos (aarch64)
self-python: cpython@3.12
symlink support: true
uv enabled: false
```

### Stacktrace

It does not crash, but this is the command run with backtrace anyway.

```
$ RUST_BACKTRACE=1 rye sync
error: failed fetching toolchain ahead of sync

Caused by:
    unknown version cpython-aarch64-macos@3.11.0

Stack backtrace:
   0: std::backtrace::Backtrace::create
   1: anyhow::error::<impl anyhow::Error>::msg
   2: rye::bootstrap::fetch
   3: rye::sync::sync
   4: rye::cli::sync::execute
   5: rye::cli::execute
   6: rye::main
   7: std::sys_common::backtrace::__rust_begin_short_backtrace
   8: std::rt::lang_start::{{closure}}
   9: std::rt::lang_start_internal
  10: _main
```

**Comment by j178** [comment]
Rye depends on `https://github.com/indygreg/python-build-standalone` for its standalone Python releases. Unfortunately, there isn't a `3.11.0` release available. You might want to consider setting the Python version to `3.11.1` or later.

**Comment by selectnull** [comment]
@j178 Thanks, that helped.

If anyone else discovers this issue with the same problem, the solution is to update `pyproject.toml` file with `requires-python = ">= 3.11.1"` and `.python-version` with `3.11.1` (or any other supported version). After that, `rye sync` works.
