### ISSUE TITLE
`sync` not using flags informations from the lock file

### ISSUE THREAD

**Issue by FelipeCybis** [astral-sh/rye#825]
Hey!

I saw this https://github.com/astral-sh/rye/pull/677, that closed this https://github.com/astral-sh/rye/issues/676, but my issue is with the fact that the autosync does not remember the `--all-features` flag. 

~~Is there a specific reason for this? When developping a package with extra features, and you want to add a new dependency doing `rye add package`, `rye` will sync and remove the optional dependencies, so you have to do `rye sync --all-features` again, for example.~~

~~My suggestion would be to have some sort of configuration option to configure sync flags, ideally a per-project option, where I can put something like this:~~

```
[tool.rye]
# sync_flag = ["--features docs", "--features plotting"]
sync_flag = ["--all-features"]
```

Actually I misread the content from the mentioned PR, but this issue still stands for the fact the `sync` command is not using the flags from the previous `sync` stored in the lock file.

Thanks for the tool, btw :)

### EDIT
Apparently you can have a workaround using what is discussed in https://github.com/astral-sh/rye/issues/818 by doing 

```
[tool.rye]
dev-dependencies = [
  "-e file:.[docs]"
]
```
but https://github.com/astral-sh/rye/issues/818#issuecomment-1972169251 says it works more or less by accident and that is why it is not documented, but maybe it would be good to have a nicer way to do it?

**Comment by mitsuhiko** [comment]
If it does not remember `--all-features` then that is a bug. I will look into it. The requirements lock file has a comment specifically to remember that flag.

**Comment by FelipeCybis** [comment]
Ok, since `rye sync` was not remembering `--all-features` I misread your text on https://github.com/astral-sh/rye/issues/676 and thought you were saying `pre`, `features`, `all-features` and `with-source` needed to be reused every `rye sync`... 

I now understood it well and looked at the `.lock` files. Indeed, there is some bug when reading the lock files.
Here is what I did:
```
rye init test
cd test
rye add numpy
# add and sync numpy
rye add --optional=plotting matplotlib
# add matplotlib, normal because sync had no flags when created the lock file
rye sync --features=plotting
# correctly sync matplotlib and writes features: ["plotting"] in the lock file
rye remove numpy
# removes everything including matplotlib
```
But then I wanted to test some more and
```
rye add numpy
rye add --optional=plotting matplotlib
# this should sync matplotlib directly because lock file still has features: ["plotting"] on it but it does not
rye sync --all-features
# correctly installs matplotlib and now lock file has features: [], all-features: true
rye sync --features=plotting
# correctly does nothing, but lock file does not change and still has features: [], all-features: true
rye remove numpy
# removes everything again
```

**Comment by cnpryer** [comment]
Potentially related comment https://github.com/astral-sh/rye/pull/811#issuecomment-1975275649

**Comment by FelipeCybis** [comment]
I edited a little bit my issue so it now points to the real issue, sorry for that

**Comment by mitsuhiko** [comment]
Found the issue. It's because the lock options are restored too late. I will fix this.
