### ISSUE TITLE
rye add with git url prematurely locks it with uv

### ISSUE THREAD

**Issue by bluss** [astral-sh/rye#828]
### Steps to Reproduce

1. rye init urldep;  cd urldep
2. rye add ryeish_kernel --git https://github.com/bluss/ryeish-kernel --branch main

### Expected Result

pyproject should contain `ryeish-kernel @ git+https://github.com/bluss/ryeish-kernel@main` in dependencies

### Actual Result

git repo/branch is resolved to fixed commit in the dependencies in pyproject.toml.
It contained `"ryeish-kernel @ git+https://github.com/bluss/ryeish-kernel@857a5450a58aea0c699d2e31772f0054af48f011",` instead, which is not what was intended.

Expected that - pyproject.toml contains the intended dependency that is just the naked git url, or with branch, tag, commit as instructed by the user.

The *lockfile* however is welcome to lock with a specific commit (and it does) - this is an already present and welcome new feature with rye+uv.

### Version Info

rye 0.27.0
commit: 0.27.0 (43ee4fce0 2024-02-26)
platform: linux (x86_64)
self-python: cpython@3.12
symlink support: true
uv enabled: true

**Comment by charliermarsh** [comment]
I think this can be solved by just skipping the `uv pip compile --no-deps` step for URL dependencies.

**Comment by mitsuhiko** [comment]
Fixed by #846
