### ISSUE TITLE
Different behavior of `rye add` when uv is on and off

### ISSUE THREAD

**Issue by dgavrilov** [astral-sh/rye#833]
### Steps to Reproduce

1. `rye config --set behavior.use-uv=true`
2. `rye add dynaconf==3.2.4`

If set `use-uv=false`, the behavior is correct.

### Expected Result

```
dependencies = [
    "dynaconf==3.2.4",
]
```

### Actual Result

```
dependencies = [
    "dynaconf>=3.2.4",
]
```

### Version Info

```
rye 0.27.0
commit: 0.27.0 (43ee4fce0 2024-02-26)
platform: windows (x86_64)
self-python: cpython@3.12
symlink support: true
uv enabled: true
```

**Comment by mitsuhiko** [comment]
I did not actually realize that the old behavior works this way. It was intended that they all turn into `>=` (or whatever `--pin` points to). But I do think that the non uv behavior might be better here.

**Comment by dgavrilov** [comment]
It seems logical to me that if I specify the exact version of a package, then the dependencies should have the exact version as well. I understand that this can be changed via `dependency-operator`, but maybe the default behavior should be like this.
