### ISSUE TITLE
Bootstrap fails after outdated internals detection

### ISSUE THREAD

**Issue by cnpryer** [astral-sh/rye#849]
### Steps to Reproduce

1. Install 0.27.0
2. Run `rye self update`
3. Run command to trigger outdated internals detection (I used `rye fmt`)

### Expected Result

Format should work.

### Actual Result

```
❯ rye fmt
Detected outdated rye internals. Refreshing
Bootstrapping rye internals
Found a compatible Python version: cpython@3.12.2
error: tried to symlink python shim (at 'C:\Users\pryerc\.rye\shims\python.exe')

Caused by:
    Cannot create a file when that file already exists. (os error 183)
```

### Version Info

```
rye 0.28.0
commit: 0.28.0 (c44dc7ec8 2024-03-07)
platform: windows (x86_64)
self-python: cpython@3.12.2
symlink support: false
uv enabled: true
```

**Comment by ischaojie** [comment]
Test on macos (aarch64):

```
➜  rye-test git:(main) ✗ rye --version
rye 0.27.0
commit: 0.27.0 (43ee4fce0 2024-02-26)
platform: macos (aarch64)
self-python: cpython@3.12
symlink support: true
uv enabled: true
➜  rye-test git:(main) ✗ rye self update
Updating to latest
Checking checksum
Updated!

rye 0.28.0
commit: 0.28.0 (c44dc7ec8 2024-03-07)
platform: macos (aarch64)
self-python: cpython@3.12.0
symlink support: true
uv enabled: true
➜  rye-test git:(main) ✗ rye fmt
Detected outdated rye internals. Refreshing
Bootstrapping rye internals
Found a compatible Python version: cpython@3.12.0
1 file reformatted

```

**Comment by cnpryer** [comment]
Yep. Can also confirm I cannot repro on Mac. Thanks for checking.

**Comment by cnpryer** [comment]
Is the expectation to update another way on Windows machines with symlinks disabled? I have not looked into this much. So I'm not sure if we expect Rye to update differently without symlinks.

**Comment by cnpryer** [comment]
From https://rye-up.com/guide/faq/#windows-developer-mode you need to expand the *"What happens if I don't enable it?"* section for:

> All shims will be installed as hardlinks. This can cause issues when upgrading Rye while Python is in use. These hardlinks will also continue to point to older Rye executables creating more hard drive usage.

I'll close this for now, but maybe we can update this to mention that upgrades will actually *fail*. Not just comment on potential storage bloat.
