### ISSUE TITLE
Crash on `rye --version | head -1`

### ISSUE THREAD

**Issue by dalf** [astral-sh/rye#861]
### Steps to Reproduce

Run `rye --version | head -1`

### Expected Result

```
rye 0.28.0
```

### Actual Result

```
rye 0.28.0
thread 'main' panicked at library/std/src/io/stdio.rs:1021:9:
failed printing to stdout: Broken pipe (os error 32)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Version Info

```
rye 0.28.0
commit: 0.28.0 (c44dc7ec8 2024-03-07)
platform: linux (x86_64)
self-python: cpython@3.12.1
symlink support: true
uv enabled: false
```

### Stacktrace

```
thread 'main' panicked at library/std/src/io/stdio.rs:1021:9:
failed printing to stdout: Broken pipe (os error 32)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: std::io::stdio::print_to
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/stdio.rs:1021:9
   3: std::io::stdio::_print
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/stdio.rs:1097:5
   4: rye::cli::print_version
   5: rye::cli::execute
   6: rye::main
```

**Comment by mitsuhiko** [comment]
Hah. You ran into one of the odd outcomes of stdio in Rust. Since `println!` is infallible it just panics when the target stream is closed which basically happens in this case. Fixing this might require replacing `println!` with a custom macro in Rye that somehow closes the process instead.

**Comment by mitsuhiko** [comment]
Really hate the solution I have in place at the moment.

For alternative approaches see https://github.com/rust-lang/rust/issues/46016

**Comment by weihanglo** [comment]
An alternative could be a custom wrapper of print macros, and disallow std marcos in clippy

https://rust-lang.github.io/rust-clippy/master/index.html#/disallowed_macros

**Comment by mitsuhiko** [comment]
Most uses of printing are already wrapped via the `echo!` macro so that would be an option.

**Comment by weihanglo** [comment]
Totally forgot. [`print_stdout`](https://rust-lang.github.io/rust-clippy/master/index.html#/print_stdout) and [`print_stderr`](https://rust-lang.github.io/rust-clippy/master/index.html#/print_stderr) lints might be better, pairing with [`allow-print-in-tests`](https://doc.rust-lang.org/nightly/clippy/lint_configuration.html#allow-print-in-tests) config. That is how Cargo does.
