### ISSUE TITLE
Alternative Package Setups

### ISSUE THREAD

**Issue by RitikShah** [astral-sh/rye#870]
Alternative package setups, such as how [poetry packages](https://python-poetry.org/docs/pyproject/#packages), was one feature I didn't realize I missed when migrating to rye. Afaik this is also doable with a vanilla `setup.py` file, but via `poetry`, it felt intentional. Would be really nice to also have for parity!

Essentially, allows me to define alternative imports that aren't based on the `pip` name. (if my package is called `smithed` but I want people to be able to do `import weld` instead of `import smithed.weld`.

**Comment by chainyo** [comment]
I think you can still do it

```toml
[tool.hatch.build.targets.wheel]
"smithed/weld" = "weld"
```

Check [this](https://hatch.pypa.io/latest/config/build/#rewriting-paths) in the hatch documentation.

**Comment by RitikShah** [comment]
Ah, thanks this works!
