### ISSUE TITLE
Rye is not added to path even after choosing add to path option

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [astral-sh/rye#874]
### Steps to Reproduce

On Linux Mint

Copy paste linux install line

Respond y when asked to add to path

### Expected Result

typing $ rye should give results

### Actual Result

rye command not found

❯ ls -alh ~/.rye/shims                                                       ─╯
total 79M
drwxrwxr-x 2 appinv appinv 4.0K Mar 12 11:41 .
drwxrwxr-x 6 appinv appinv 4.0K Mar 12 11:41 ..
-rwxrwxr-x 3 appinv appinv  27M Mar 12 11:39 python
-rwxrwxr-x 3 appinv appinv  27M Mar 12 11:39 python3
-rwxrwxr-x 3 appinv appinv  27M Mar 12 11:39 rye

### Version Info

idk

**Comment by Abdur-rahmaanJ** [comment]
Fixed it for now by manually adding the shim path to bashrc

**Comment by dsp** [comment]
Can you add a few more details please?

1. What shell are you using?
2. Can you reproduce it (Remove ~/.rye, remove ~/.rye from $PATH, reinstall rye)?
3. Do you remember if you received the message: "Added to PATH", while installing rye?

**Comment by Abdur-rahmaanJ** [comment]
shell: oh my zsh
