### ISSUE TITLE
Support for platform indipendent lockfile and SHA-pinning

### ISSUE THREAD

**Issue by csuriano23** [astral-sh/rye#881]
Hi there,
thank you for the great effort put into this amazing project.

I'm asking whether you plan in the future (maybe when `uv` support won't no longer be experimental) to overcome the [current limitations](https://rye-up.com/guide/sync/#limitations) in order to being able to:

- Generate a platform-indipendent lockfile
- Pin the dependency version by SHA. You can already do that with pip-tools (option `--generate-hashes`), but apparently this is not available inside the rye CLI
- Check for outdated dependencies (like you can do with pip: `pip list --outdated`)

**Comment by mitsuhiko** [comment]
Yep, this is planned. But the plumbing for this will be in uv so until then I will close this as there are already issues for it.

**Comment by DetachHead** [comment]
is there an issue on uv for this? i couldn't find one so i raised https://github.com/astral-sh/uv/issues/2679
