### ISSUE TITLE
`rye tools install` didn't install all scripts

### ISSUE THREAD

**Issue by ayush--s** [astral-sh/rye#896]
### Steps to Reproduce

```
❯ rye tools install ansible
Resolved 10 packages in 2.59s
Downloaded 10 packages in 10.53s
Installed 10 packages in 887ms
 + ansible==9.3.0
 + ansible-core==2.16.4
 + cffi==1.16.0
 + cryptography==42.0.5
 + jinja2==3.1.3
 + markupsafe==2.1.5
 + packaging==24.0
 + pycparser==2.21
 + pyyaml==6.0.1
 + resolvelib==1.0.1

Installed scripts:
  - ansible-community

note: additional scripts were encountered in non-installed dependencies.
```

### Expected Result

there are more scripts in ansible package: https://github.com/ansible/ansible/blob/devel/setup.py#L18-L27

### Actual Result

```
❯ rye tools list -sv
ansible 9.3.0 (cpython@3.12.2)
  ansible-community
```

### Version Info

```
❯ rye --version
rye 0.29.0
commit: 0.29.0 (2024-03-11)
platform: macos (x86_64)
self-python: cpython@3.12.2
symlink support: true
uv enabled: true
```

**Comment by j178** [comment]
`ansible` only comes with `ansible-community` script, additional scirpts like `ansible`, `ansible-console` are all from `ansible-core`. Currenly you have to use `rye tools install ansible -f --include-dep ansible-core` to install all the scripts.

**Comment by mitsuhiko** [comment]
Closing this as non actionable. The installation tool works as documented, there might be improvements that could be done but ultimately that's up to the package.
