### ISSUE TITLE
Workspace deps have empty pth file and can't be imported

### ISSUE THREAD

**Issue by konstin** [astral-sh/rye#907]
Reproducer repo: https://github.com/konstin/albatross

I have a workspace with a main library and a workspace package the main package depends on, both created with `rye init`:
```
.
├── Dockerfile
├── providers
│   └── pypi_provider
│       ├── pyproject.toml
│       ├── README.md
│       └── src
│           └── pypi_provider
│               └── __init__.py
├── pyproject.toml
├── README.md
├── requirements-dev.lock
├── requirements.lock
└── src
    └── albatross
        └── main.py
```

After running `rye sync`, i get a `.venv/lib/python3.11/site-packages/_albatross.pth` with the correct `/home/konsti/projects/albatross/src`, while `.venv/lib/python3.11/site-packages/_pypi_provider.pth` is incorrectly empty, so the `pypi_provider` can't be imported.

The linked repo contains a dockerfile reproducing this problem. The problems happens with both pip and uv, latest release and b290caed2a7b5d38cc4c8defc53912b41b8039ad.

**Comment by mitsuhiko** [comment]
No clue what triggers this, but I cannot reproduce this with `setuptools`, only with `hatchling` :-/ `setuptools` does the right thing:

```
$ cat .venv/lib/python3.11/site-packages/__editable__.*.pth
/private/tmp/albatross/src
/private/tmp/albatross/providers/pypi_provider/src
```

**Comment by mitsuhiko** [comment]
Found a closed issues on hatch which implies that something has been fixed:

* https://github.com/pypa/hatch/issues/860

**Comment by mitsuhiko** [comment]
Can be reproduced with `uv directly` by just running `uv pip sync requirements.lock`.

**Comment by bluss** [comment]
I notice that your nested pyproject contains

```
[tool.hatch.build.targets.wheel]
packages = ["src/pypi"]
```
but this doesn't match the source directory which is src/pypi_provider? I could be mistaken, but worth recreating the project or checking this.

**Comment by mitsuhiko** [comment]
Yap. That fixes it. Would be nice if hatch would print out something useful there or error :(
