### ISSUE TITLE
`rye build` error on MacOS: No module named build 

### ISSUE THREAD

**Issue by MikulasZelinka** [astral-sh/rye#939]
### Steps to Reproduce

Install `rye`, create an empty project using `rye init` and then run `rye build`.

### Expected Result

`rye build` should work: https://rye-up.com/guide/publish/

### Actual Result

```
❯ rye build    
building <package_name>
/Users/<user>/.rye/self/bin/python: No module named build
error: failed to build dist
```

### Version Info

```
❯ rye --version
rye 0.31.0
commit: 0.31.0 (72e239b8f 2024-03-22)
platform: macos (aarch64)
self-python: cpython@3.12.2
symlink support: true
uv enabled: true
```

**Comment by MikulasZelinka** [comment]
This only happens on MacOS, the same version of `rye` works just fine in the same project on Windows:

```
❯ rye --version
rye 0.31.0
commit: 0.31.0 (72e239b8f 2024-03-22)
platform: windows (x86_64)
self-python: cpython@3.12.2
symlink support: true
uv enabled: true
```

**Comment by bluss** [comment]
I can't reproduce this (same self-python and same rye version on macos)

**Comment by MikulasZelinka** [comment]
Fixed by uninstalling (`rye self update` didn't help):

```bash
rye self uninstall
```

and then downloading and installing rye (`0.32.0`) again:

```bash
curl -sSf https://rye-up.com/get | bash
```
