### ISSUE TITLE
rye list overwrites .venv 

### ISSUE THREAD

**Issue by bluss** [astral-sh/rye#940]
### Steps to Reproduce

1. Enter a non-rye managed project that has pyproject.toml and .venv
2. rye list

(for example with PDM: `mkdir project; cd project; pdm init -n; pdm add jinja2; pdm list; rye list; pdm list;` )

### Expected Result

rye list should error or make a best effort to list the packages in the project.

rye list should not wipe out .venv directories that rye is not managing. rye list should preferably never do any modifications at all, it's a query command.

### Actual Result

It overwrites .venv with a fresh venv (created with uv venv), wiping anything that was there before.

```
Using Python 3.10.12 interpreter at: .venv/bin/python
Creating virtualenv at: .venv
Activate with: source .venv/bin/activate
```

### Version Info

rye 0.31.0
commit: 0.31.0 (72e239b8f 2024-03-22)
platform: linux (x86_64)
self-python: cpython@3.12.2
symlink support: true
uv enabled: true

**Comment by ischaojie** [comment]
It seems that PDM does a good job in this regard. If it is a project created by rye, `pdm list` will still output the correct content.

**Comment by bluss** [comment]
When I try the pdm command in the report now, it gives something like this error instead of overwrite, from rye list:

```
error: unable to freeze venv at /home/ulrik/ryes/rye-overwrite-test/project/.venv

Caused by:
    Permission denied (os error 13)
```

but other sequences like `rm -r .venv; uv sync; rye list` still lead to overwriting the existing .venv.

**Comment by bluss** [comment]
This permission denied error cannot be reproduced, that's bad. Now I'm puzzled!

**Comment by bluss** [comment]
The follow-up is #1352. It's more contrieved, but maybe still a bug.
