### ISSUE TITLE
Trying to install on an offline machine (has a pypi mirror)

### ISSUE THREAD

**Issue by nazq** [astral-sh/rye#941]
### Steps to Reproduce

1. Copy the linux bin from https://github.com/astral-sh/rye/releases/latest/download/rye-x86_64-linux.gz and copy to machine
2. decompress and run (tried both with RYE_NO_AUTO_INSTALL=1 and without)
3. point to a custom python toolchain
4. Create a trivial pyproject.toml with a few deps (can use uv on this directly)
5. Hangs at "Bootstrapping rye internals"

Took a look at this issue but did not solve it for me
https://github.com/astral-sh/rye/issues/393

ls -l ~/.rye/
config.toml   env   py/   shims/

cat ~/.rye/config.toml
[behavior]
use-uv = true

[default]
toolchain = "py39"

rye toolchain list
py39@3.9.16 (/usr/bin/python3.9)

### Expected Result

Expected `rye install` to work. Does on my online machine

### Actual Result

Hangs at "Bootstrapping rye internals"

### Version Info

rye == 0.31.0
platform linux x_86_64

**Comment by nazq** [comment]
Tried one more thing. 
rm -rf ~/.rye
RYE_NO_AUTOINSTALL=1 rye self install --toolchain /usr/bin/python3.9

...
...
Installed binary to /home/userX/.rye/shims/rye
Registering toolchain at /usr/bin/python3.9
Registered toolchain as cpython@3.9.16
Bootstrapping rye internals
error: download of https://github.com/astral-sh/uv/....

I then did a look at my online install and manually procured the uv binary and placed it in ~/.rye/uv/0.1.23/ then re-ran

This time it gets past the  "Bootstrapping rye internals" step, then prints
"Found a compatible Python version: cpython@3.9.16"

Then seems to hang again, likely on a network call. Been watching this for 10-15 mins now. Will report if it gives any useful output

**Comment by nazq** [comment]
Finally failed, looks like it was trying to hit pypi.org. Ideally I'd want to be able to pass a --index-url to point to my internal mirror.

Thanks

**Comment by nazq** [comment]
I did try and add my config.toml in advance with 

[[sources]]
name = "my_pypi"
url = "https://myspecialendpoint/simple/"

but still the same

**Comment by nazq** [comment]
After a few experiments probably worth a recap. So 

1. I start with a clean ~/.rye, and the rye 0.31.0 linux x86_64 binary
2. I add a config.toml to the ~/.rye/ with 
[behaviour]
use-uv = true

[[sources]]
name = "my_pypi"
url = "https://myspecialendpoint/simple/"

3. Run `RYE_NO_AUTO_INSTALL=1 rye self install --toolchain /usr/bin/python3.9`
4. output (typing it so I will truncate) is
Installed binary to ... ~/.rye/shims/rye
Registered toolchain at /usr/bin/python3.9
Registered toolchain as cpython@3.9.16
Bootstrapping rye internals
Found a compatible python version: cpython@3.9.16

_then hangs, I suspect waiting on pypi.org which it won't be able to hit_

**Comment by bluss** [comment]
It's trying to install these into .rye/self venv from pypi: https://github.com/astral-sh/rye/blob/153213c6af75651c63d97ae1082471c43dfa80e1/rye/src/bootstrap.rs#L37-L55

**Comment by nazq** [comment]
Thanks for this @bluss. I tried to create the env with uv, then sync these deps into there but it gets overwritten. Looking at uv.rs it seems there is a builder which allows creating the uv env with ExpandedSources. I suspect the bootstrap should take an --index-url param and use the builder to ensure it can sync the nec pkgs

**Comment by bluss** [comment]
@nazq can you maybe set an environment variable for uv index url for that step?

**Comment by nazq** [comment]
Great idea. Tried the following

UV_INDEX_URL=https://myspecial-pypi/pypi/simple RYE_NO_AUTO_INSTALL=1 rye self install --toolchain /usr/bin/python3.9

But it still looks like it's trying to hit pypi.org

**Comment by nazq** [comment]
I take that back. I had forgotten to copy uv into the ~/.rye ... looks like I'm up and running. Many thanks

**Comment by vladjohnson** [comment]
@nazq running into the similar issue: 

After `rye sync`, it is stuck at "Bootstrapping rye internals". Tried tcpdump and it is trying to send a request to github.com. Since we are in a locked environment, only pypi mirror is accessible. Any suggestions on how to solve this? Thanks!

**Comment by vladjohnson** [comment]
@nazq, I've placed binaries into `~/.rye/uv/0.3.5`, but Rye is not still seeing UV and hangs at "Bootstrapping rye internals"... any ideas?
