### ISSUE TITLE
command to get the current project version

### ISSUE THREAD

**Issue by DetachHead** [astral-sh/rye#946]
pdm has a command to get the current version of the package from `pyproject.toml`:

```
pdm show --version
```

this is good for the CI since i use it to automatically generate a github release. it would be nice if rye had a command for this too.

# workaround

```
rye run python -c "import tomllib, pathlib;print(tomllib.loads(pathlib.Path('pyproject.toml').read_text())['project']['version'])
```

**Comment by ischaojie** [comment]
```
rye version
```

**Comment by DetachHead** [comment]
how did i miss that? thanks!
